easy_admin:
    entities:
#        # List the entity class name you want to manage
        BlogPost:
            class: App\Entity\BlogPost 
        Comment:
            class: App\Entity\Comment
        Image:
            class: App\Entity\Image
        User:
            class: App\Entity\User
            controller: App\Controller\UserAdminController

